# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Knb001Nc-mMftUCVyWNs0zm-K4gxvj07
"""

"Hello world "
nome = "Luana"
idade = "30"

# Fix: Delete the 'print' variable to restore the built-in print function.
# This assumes 'print' was mistakenly assigned a string value earlier.
# If this causes issues with other parts of the notebook, consider restarting the kernel.
del print

print("meu nome é",nome)
print ("Eu tenho", idade,"anos")

#salvar o notebook como arquivo python

cidade = "hamburgo"
print ("eu moro",cidade)

! pip install datasets

from datasets import load_dataset

# Baixa o dataset de Spotify
dataset = load_dataset("maharshipandya/spotify-tracks-dataset")

# Converte para DataFrame pandas
df = dataset["train"].to_pandas()
df.head()

df.head ()

#mostrar as10 primeiras músicas do dataset
df[['track_name', 'artists', 'popularity']].head(10)

from datasets import load_dataset

# Baixa o dataset de Spotify
dataset = load_dataset("maharshipandya/spotify-tracks-dataset")

# Converte para DataFrame pandas
df = dataset["train"].to_pandas()
df.head()